### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'search'

### ISSUE THREAD

**Issue by max3903** [moturi12/shared_public_addons_v7#1]
I installed Ru3ix Aged Partner Balance module on version 7.
I configure aging period with 30 days.
I have 2 open invoices.
When I generate the report, I checked "Detailed report" and try to print the PDF.

I get the following error on the screen:

```
SyntaxError: JSON.parse: unexpected end of data at line 2 column 1 of the JSON data
```

and this one in the log:

```
2015-05-26 15:36:50,036 14416 ERROR SFL openerp.tools.safe_eval: Cannot eval " (get_lines(data['form']), 'partner') == False or removeParentNode('para')  "
Traceback (most recent call last):
  File "/home/max/openerp/sfl/git/odoo/openerp/tools/safe_eval.py", line 287, in safe_eval
    return eval(test_expr(expr, _SAFE_OPCODES, mode=mode), globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 319, in _get_lines
    inlines=self._display_screen(partner['id'],form,current_records)
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 383, in _display_screen
    payment_ids = payment_display.search(cr,uid,[('partner_id','=',ids[0])])
AttributeError: 'NoneType' object has no attribute 'search'
2015-05-26 15:36:50,037 14416 WARNING SFL openerp.report.render.rml2pdf.utils: rml_except: " (get_lines(data['form']), 'partner') == False or removeParentNode('para')  "
Traceback (most recent call last):
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/utils.py", line 76, in _child_get
    eval(n.get('rml_except'), {}, self.localcontext)
  File "/home/max/openerp/sfl/git/odoo/openerp/tools/safe_eval.py", line 287, in safe_eval
    return eval(test_expr(expr, _SAFE_OPCODES, mode=mode), globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 319, in _get_lines
    inlines=self._display_screen(partner['id'],form,current_records)
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 383, in _display_screen
    payment_ids = payment_display.search(cr,uid,[('partner_id','=',ids[0])])
AttributeError: 'NoneType' object has no attribute 'search'
2015-05-26 15:36:50,080 14416 ERROR SFL openerp.tools.safe_eval: Cannot eval "repeatIn(get_lines(data['form']), 'partner')"
Traceback (most recent call last):
  File "/home/max/openerp/sfl/git/odoo/openerp/tools/safe_eval.py", line 287, in safe_eval
    return eval(test_expr(expr, _SAFE_OPCODES, mode=mode), globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 319, in _get_lines
    inlines=self._display_screen(partner['id'],form,current_records)
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 383, in _display_screen
    payment_ids = payment_display.search(cr,uid,[('partner_id','=',ids[0])])
AttributeError: 'NoneType' object has no attribute 'search'
2015-05-26 15:36:50,080 14416 ERROR SFL openerp.service.web_services: Exception: 'NoneType' object has no attribute 'search'
Traceback (most recent call last):
  File "/home/max/openerp/sfl/git/odoo/openerp/service/web_services.py", line 718, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/report_sxw.py", line 449, in create
    fnct_ret = fnct(cr, uid, ids, data, report_xml, context)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/report_sxw.py", line 518, in create_source_pdf
    return self.create_single_pdf(cr, uid, ids, data, report_xml, context)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/report_sxw.py", line 540, in create_single_pdf
    pdf = create_doc(etree.tostring(processed_rml),rml_parser.localcontext,logo,title.encode('utf8'))
  File "/home/max/openerp/sfl/git/odoo/openerp/report/interface.py", line 206, in create_pdf
    obj.render()
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/render.py", line 59, in render
    self._result = self._render()
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml.py", line 41, in _render
    return rml2pdf.parseNode(self.rml, self.localcontext, images=self.bin_datas, path=self.path,title=self.title)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/trml2pdf.py", line 1044, in parseNode
    r.render(fp)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/trml2pdf.py", line 331, in render
    pt_obj.render(el)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/trml2pdf.py", line 1015, in render
    fis += r.render(node_story)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/trml2pdf.py", line 906, in render
    return process_story(node_story)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/trml2pdf.py", line 899, in process_story
    flow = self._flowable(node)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/trml2pdf.py", line 766, in _flowable
    return self._pto(node)
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/trml2pdf.py", line 747, in _pto
    for node in utils._child_get(node, self):
  File "/home/max/openerp/sfl/git/odoo/openerp/report/render/rml2pdf/utils.py", line 48, in _child_get
    for ctx in eval(n.get('rml_loop'),{}, self.localcontext):
  File "/home/max/openerp/sfl/git/odoo/openerp/tools/safe_eval.py", line 287, in safe_eval
    return eval(test_expr(expr, _SAFE_OPCODES, mode=mode), globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 319, in _get_lines
    inlines=self._display_screen(partner['id'],form,current_records)
  File "/home/max/openerp/sfl/git/sfl/addons/r3x_aged_partner_balance/report/old_account_aged_partner_balance.py", line 383, in _display_screen
    payment_ids = payment_display.search(cr,uid,[('partner_id','=',ids[0])])
AttributeError: 'NoneType' object has no attribute 'search'
2015-05-26 15:36:50,225 14416 ERROR SFL openerp.netsvc: 'NoneType' object has no attribute 'search'
(<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'search'",), <traceback object at 0x7f53cb974e18>)
Traceback (most recent call last):
  File "/home/max/openerp/sfl/git/odoo/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/max/openerp/sfl/git/odoo/openerp/service/web_services.py", line 660, in dispatch
    res = fn(db, uid, *params)
  File "/home/max/openerp/sfl/git/odoo/openerp/service/web_services.py", line 766, in exp_report_get
    return self._check_report(report_id)
  File "/home/max/openerp/sfl/git/odoo/openerp/service/web_services.py", line 744, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/home/max/openerp/sfl/git/odoo/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u"'NoneType' object has no attribute 'search'", (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'search'",), <traceback object at 0x7f53cb974e18>))
```

**Comment by moturi12** [comment]
Hi Maxime - The issue is fixed and also cleaned up the code to remove the dependencies on our customer statements, please download the latest files, they should be fine. Please let me know.

-Naran

**Comment by moturi12** [comment]
Hi Maxime - Did you had a chance to test the latest module, if all ok I will close this issue.

-Naran

**Comment by max3903** [comment]
I will try again next week. I am busy at the Odoo Experience this week. Thanks.

**Comment by max3903** [comment]
@moturi12 I still have the same issue with the same error message.
